import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@radix-ui/themes/styles.css';
import './theme-config.css'
import "./globals.css";
import Navbar from "./components/Navbar";
import { Theme } from '@radix-ui/themes';
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/providers/QueryProvider";
import SessionProvider from "@/providers/SessionProvider";


const inter = Inter({ subsets: ["latin"],variable: '--font-inter', });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <SessionProvider>
          <QueryProvider>
            <Theme accentColor="purple" >
              <Toaster/>
            <Navbar/>
                <main className="py-5 px-5 sm:px-10">
                {children}
                </main>
            </Theme>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
